name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install dependencies
        run: |
          pip install poetry
          make install

      - name: Run linter and tests
        run: |
          make check
      
      - name: Run test coverage
        run: |
          make test-coverage
      
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=AlishaEvergreen_python-project-50
            -Dsonar.organization=alishaevergreen
            -Dsonar.python.coverage.reportPaths=coverage.xml
